version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fussballde-machtkalender-scraper-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    # Mount the project for quick iteration; comment out in production
    volumes:
      - ./:/app
      - ./.cache_fussballde:/app/.cache_fussballde
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
    restart: unless-stopped
