name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; else pip install ruff pylint; fi

      - name: Export PYTHONPATH
        run: echo "PYTHONPATH=." >> $GITHUB_ENV

      - name: Ruff (lint only)
        run: |
          ruff check . --output-format=github

      - name: Pylint (only Errors/Fatals)
        run: |
          pylint app tests --disable=C,R,W --fail-under=10
